
export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <h2>this UI is from Dashboard Layout</h2>
        {children}
      </body>
    </html>
  );
}
